apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: soccer
build:
  artifacts:
  - image: midfieldmagician254/soccer-auth
    context: auth
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: 'src/**/*.ts'
          dest: .
  - image: midfieldmagician254/soccer-client
    context: client
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: '**/*.js'
          dest: .
deploy:
  kubectl:
    manifests:
    - infra/k8s-dev/*
