apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: soccer
build:
  googleCloudBuild:
    projectId: soccer-317809
  artifacts:
    - image: gcr.io/soccer-317809/soccer-auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: gcr.io/soccer-317809/soccer-soccerfield
      context: soccerfield
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: gcr.io/soccer-317809/soccer-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
deploy:
  kubectl:
    manifests:
      - infra/k8s-dev/*
