POST http://lamproject.xyz/api/auth/signup
Content-Type: application/json

{
  "name": "lam",
  "username": "lamdao",
  "email": "lam@gmail.com",
  "password": "12345"
}

###
POST http://lamproject.xyz/api/auth/login
Content-Type: application/json

{
  "email": "lam@gmail.com",
  "password": "12345"
}

###
GET http://lamproject.xyz/api/auth/currentUser
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXJyZW50VXNlciI6eyJuYW1lIjoibGFtIiwidXNlcm5hbWUiOiJsYW1kYW8iLCJlbWFpbCI6ImxhbUBnbWFpbC5jb20iLCJpZCI6IjYwZDFhMmYwZmEwNjdmMTY2NGExODYzZCJ9LCJpYXQiOjE2MjQ5MzQ0NzQsImV4cCI6MTYyNDkzNDUzNH0.TbUQL5cyNHm30M9opqykhZM51Y88PyidVbqoqA9JQBU

POST http://lamproject.xyz/api/auth/login
Content-Type: application/json
