POST http://localhost:3001/api/auth/signup
Content-Type: application/json

{
  "name": "lam",
  "username": "lamdao",
  "email": "lam@gmail.com",
  "password": "12345"
}

###
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
  "email": "lam@gmail.com",
  "password": "12345"
}

###
GET http://localhost:3001/api/auth/currentUser
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXJyZW50VXNlciI6eyJuYW1lIjoibGFtIiwidXNlcm5hbWUiOiJsYW1kYW8iLCJlbWFpbCI6ImxhbUBnbWFpbC5jb20iLCJpZCI6IjYwZDA2ZjMwNjE4MjIyMjAxOWQyN2EzOSJ9LCJpYXQiOjE2MjQzNDY1NTAsImV4cCI6MTYyNDM0NjYxMH0.Z0HUOkPHnyDG-SpnGaKf__EqqOGJjzgYr4hiGYzN84I